### ISSUE TITLE
delete the dumy content 

### ISSUE THREAD

**Issue by OU4** [wkocjan/gatsby-contentful-portfolio#1]
Thanks for your effort on this template, my question please how could I delete the dummy contentful content like Iceland, Spain due to when I deleted from contentful or the json file it shows an error so could you please tell me how can I deleted it.
Thanks.

**Comment by wkocjan** [comment]
Thanks,

It was indeed required to have at least 1 item in Contentful added, but I've just fixed it in today's commits:

https://github.com/wkocjan/gatsby-contentful-portfolio/commit/e5ba24f3e40a37a2686f3d8714ea085bf14ab2b2
https://github.com/wkocjan/gatsby-contentful-portfolio/commit/22a9238401c04a96b0dc799869554b72d1949e33

Please get the latest changes from the repo and it should help.

**Comment by OU4** [comment]
Your help is much appreciated, after revising the gatsby-node.js the description section is not shows

**Comment by wkocjan** [comment]
Thanks for spotting it. I've just pushed a fix: https://github.com/wkocjan/gatsby-contentful-portfolio/commit/790e3ec190edc920e0e69bc793809527ce8adc30

Can you please confirm it helps?

**Comment by OU4** [comment]
Yes thanks, it works fine now

**Comment by wkocjan** [comment]
Great, thanks! Closing the issue then.
