### ISSUE TITLE
Hi, how i can edit import to netlify cms

### ISSUE THREAD

**Issue by soportedontec** [wkocjan/gatsby-contentful-portfolio#2]
HI, thanks for your amaizing portfollio, but i would like to edit the content on netlify cms, can u help me

**Comment by wkocjan** [comment]
Hey, thanks for kind words.

I don't have any experience with Netlify CMS, so can't prepare a step-by-step tutorial for you.

However, I expect it shouldn't be very complicated. First you'd need to get rid of `gatsby-source-contentful` plugin and then replace it by a plugin for Netlify CMS. Gatsby has really good documentation about it: https://www.gatsbyjs.org/docs/sourcing-from-netlify-cms/

Good luck!
