### ISSUE TITLE
Difficulty deploying on Netlify when it works locally

### ISSUE THREAD

**Issue by piyawill** [wkocjan/gatsby-contentful-portfolio#4]
Hello,

Thank you so much for this amazing Gatsby starter. I love it, and it is exactly what I have been looking for! It is logically designed and very clean and simple!

However, when I try to deploy the site on Netlify, the build fails. It does seem to build correctly locally, using either `gatsby build` or `gatsby develop`.

I am pasting the deploy log below, but I don't know if this is helpful. Please let me know if I can do anything else. Again, thank you so much.

> 8:01:20 PM: Build ready to start
> 8:01:24 PM: build-image version: b0258b965567defc4a2d7e2f2dec2e00c8f73ad6
> 8:01:24 PM: build-image tag: v3.4.1
> 8:01:24 PM: buildbot version: 8c957a6d09a03023cea4239847cc73a9cb64eeb7
> 8:01:24 PM: Fetching cached dependencies
> 8:01:24 PM: Failed to fetch cache, continuing with build
> 8:01:24 PM: Starting to prepare the repo for build
> 8:01:25 PM: No cached dependencies found. Cloning fresh repo
> 8:01:25 PM: git clone https://github.com/piyawill/portfolio
> 8:01:26 PM: Preparing Git Reference refs/heads/master
> 8:01:27 PM: Different publish path detected, going to use the one specified in the Netlify configuration file: 'public' versus 'public/' in the Netlify UI
> 8:01:27 PM: Starting build script
> 8:01:27 PM: Installing dependencies
> 8:01:27 PM: Python version set to 2.7
> 8:01:29 PM: v12.18.0 is already installed.
> 8:01:30 PM: Now using node v12.18.0 (npm v6.14.4)
> 8:01:30 PM: Started restoring cached build plugins
> 8:01:30 PM: Finished restoring cached build plugins
> 8:01:30 PM: Attempting ruby version 2.7.1, read from environment
> 8:01:31 PM: Using ruby version 2.7.1
> 8:01:32 PM: Using PHP version 5.6
> 8:01:32 PM: 5.2 is already installed.
> 8:01:32 PM: Using Swift version 5.2
> 8:01:32 PM: Started restoring cached node modules
> 8:01:32 PM: Finished restoring cached node modules
> 8:01:32 PM: Installing NPM modules using NPM version 6.14.4
> 8:02:50 PM: > sharp@0.25.4 install /opt/build/repo/node_modules/sharp
> 8:02:50 PM: > (node install/libvips && node install/dll-copy && prebuild-install --runtime=napi) || (node-gyp rebuild && node install/dll-copy)
> 8:02:50 PM: info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.9.1/libvips-8.9.1-linux-x64.tar.gz
> 8:02:53 PM: > core-js@2.6.11 postinstall /opt/build/repo/node_modules/babel-runtime/node_modules/core-js
> 8:02:53 PM: > node -e "try{require('./postinstall')}catch(e){}"
> 8:02:53 PM: > core-js@3.6.5 postinstall /opt/build/repo/node_modules/core-js
> 8:02:53 PM: > node -e "try{require('./postinstall')}catch(e){}"
> 8:02:54 PM: > core-js-pure@3.6.5 postinstall /opt/build/repo/node_modules/core-js-pure
> 8:02:54 PM: > node -e "try{require('./postinstall')}catch(e){}"
> 8:02:56 PM: > gatsby-telemetry@1.3.34 postinstall /opt/build/repo/node_modules/gatsby-telemetry
> 8:02:56 PM: > node src/postinstall.js || true
> 8:02:56 PM: > mozjpeg@7.0.0 postinstall /opt/build/repo/node_modules/mozjpeg
> 8:02:56 PM: > node lib/install.js
> 8:02:57 PM:   ✔ mozjpeg pre-build test passed successfully
> 8:02:57 PM: > pngquant-bin@6.0.0 postinstall /opt/build/repo/node_modules/pngquant-bin
> 8:02:57 PM: > node lib/install.js
> 8:02:57 PM:   ✔ pngquant pre-build test passed successfully
> 8:02:57 PM: > gatsby-cli@2.12.97 postinstall /opt/build/repo/node_modules/gatsby/node_modules/gatsby-cli
> 8:02:57 PM: > node scripts/postinstall.js
> 8:02:57 PM: > gatsby@2.24.60 postinstall /opt/build/repo/node_modules/gatsby
> 8:02:57 PM: > node scripts/postinstall.js
> 8:02:58 PM: > swiper@5.4.5 postinstall /opt/build/repo/node_modules/swiper
> 8:02:58 PM: > echo "Love Swiper? Support Vladimir's work by donating or pledging on patreon: > https://patreon.com/vladimirkharlampidi
> 8:02:58 PM: "
> 8:02:58 PM: Love Swiper? Support Vladimir's work by donating or pledging on patreon: > https://patreon.com/vladimirkharlampidi
> 8:02:58 PM: > gatsby-contentful-portfolio@1.0.0 postinstall /opt/build/repo
> 8:02:58 PM: > node ./bin/hello.js
> 8:02:58 PM: Hey there! 👋
> 8:02:58 PM: Thanks for giving the gatsby-contentful-portfolio a try. 🎉
> 8:02:58 PM: To get you going really quickly this project includes a setup step.
> 8:02:58 PM: npm run setup automates the following steps for you:
> 8:02:58 PM:   - creates a config file .env
> 8:02:58 PM:   - imports a predefined content model
> 8:02:58 PM: When this is done run:
> 8:02:58 PM: gatsby develop to start a development environment at localhost:8000
> 8:02:58 PM: or
> 8:02:58 PM: gatsby build to create a production ready static site in ./public
> 8:03:01 PM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
> 8:03:01 PM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> 8:03:01 PM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
> 8:03:01 PM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> 8:03:01 PM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/babel-plugin-add-module-exports/node_modules/fsevents):
> 8:03:01 PM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> 8:03:01 PM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
> 8:03:01 PM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> 8:03:01 PM: added 3142 packages from 2035 contributors and audited 3156 packages in 88.429s
> 8:03:04 PM: 175 packages are looking for funding
> 8:03:04 PM:   run `npm fund` for details
> 8:03:04 PM: found 7 vulnerabilities (2 low, 5 high)
> 8:03:04 PM:   run `npm audit fix` to fix them, or `npm audit` for details
> 8:03:04 PM: NPM modules installed
> 8:03:05 PM: Started restoring cached go cache
> 8:03:05 PM: Finished restoring cached go cache
> 8:03:05 PM: go version go1.14.4 linux/amd64
> 8:03:05 PM: go version go1.14.4 linux/amd64
> 8:03:05 PM: Installing missing commands
> 8:03:05 PM: Verify run directory
> 8:03:06 PM: ​
> 8:03:06 PM: ┌─────────────────────────────┐
> 8:03:06 PM: │        Netlify Build        │
> 8:03:06 PM: └─────────────────────────────┘
> 8:03:06 PM: ​
> 8:03:06 PM: ❯ Version
> 8:03:06 PM:   @netlify/build 3.3.5
> 8:03:06 PM: ​
> 8:03:06 PM: ❯ Flags
> 8:03:06 PM:   deployId: 5f6163e04af55900083f6cb4
> 8:03:06 PM:   mode: buildbot
> 8:03:06 PM: ​
> 8:03:06 PM: ❯ Current directory
> 8:03:06 PM:   /opt/build/repo
> 8:03:06 PM: ​
> 8:03:06 PM: ❯ Config file
> 8:03:06 PM:   No config file was defined: using default values.
> 8:03:06 PM: ​
> 8:03:06 PM: ❯ Context
> 8:03:06 PM:   production
> 8:03:06 PM: ​
> 8:03:06 PM: ┌───────────────────────────────────┐
> 8:03:06 PM: │ 1. Build command from Netlify app │
> 8:03:06 PM: └───────────────────────────────────┘
> 8:03:06 PM: ​
> 8:03:06 PM: $ gatsby build
> 8:03:09 PM: error We encountered an error while trying to load your site's gatsby-config. Please fix the error and try again.
> 8:03:09 PM: 
> 8:03:09 PM:   Error: Contentful space ID and the access token need to be provided.
> 8:03:09 PM:   
> 8:03:09 PM:   - gatsby-config.js:6 Object.<anonymous>
> 8:03:09 PM:     /opt/build/repo/gatsby-config.js:6:9
> 8:03:09 PM:   
> 8:03:09 PM:   - v8-compile-cache.js:178 Module._compile
> 8:03:09 PM:     [repo]/[v8-compile-cache]/v8-compile-cache.js:178:30
> 8:03:09 PM:   
> 8:03:09 PM:   - loader.js:1158 Object.Module._extensions..js
> 8:03:09 PM:     internal/modules/cjs/loader.js:1158:10
> 8:03:09 PM:   
> 8:03:09 PM:   - loader.js:986 Module.load
> 8:03:09 PM:     internal/modules/cjs/loader.js:986:32
> 8:03:09 PM:   
> 8:03:09 PM:   - loader.js:879 Function.Module._load
> 8:03:09 PM:     internal/modules/cjs/loader.js:879:14
> 8:03:09 PM:   
> 8:03:09 PM:   - loader.js:1026 Module.require
> 8:03:09 PM:     internal/modules/cjs/loader.js:1026:19
> 8:03:09 PM:   
> 8:03:09 PM:   - v8-compile-cache.js:159 require
> 8:03:09 PM:     [repo]/[v8-compile-cache]/v8-compile-cache.js:159:20
> 8:03:09 PM:   
> 8:03:09 PM:   - get-config-file.ts:30 getConfigFile
> 8:03:09 PM:     [repo]/[gatsby]/src/bootstrap/get-config-file.ts:30:20
> 8:03:09 PM:   
> 8:03:09 PM:   - initialize.ts:113 initialize
> 8:03:09 PM:     [repo]/[gatsby]/src/services/initialize.ts:113:50
> 8:03:09 PM:   
> 8:03:09 PM:   - index.ts:40 bootstrap
> 8:03:09 PM:     [repo]/[gatsby]/src/bootstrap/index.ts:40:15
> 8:03:09 PM:   
> 8:03:09 PM:   - build.ts:89 build
> 8:03:09 PM:     [repo]/[gatsby]/src/commands/build.ts:89:47
> 8:03:09 PM:   
> 8:03:09 PM: 
> 8:03:09 PM: not finished open and validate gatsby-configs - 0.064s
> 8:03:09 PM: ​
> 8:03:09 PM: ┌─────────────────────────────┐
> 8:03:09 PM: │   "build.command" failed    │
> 8:03:09 PM: └─────────────────────────────┘
> 8:03:09 PM: ​
> 8:03:09 PM:   Error message
> 8:03:09 PM:   Command failed with exit code 1: gatsby build
> 8:03:09 PM: ​
> 8:03:09 PM:   Error location
> 8:03:09 PM:   In Build command from Netlify app:
> 8:03:09 PM:   gatsby build
> 8:03:09 PM: ​
> 8:03:09 PM:   Resolved config
> 8:03:09 PM:   build:
> 8:03:09 PM:     command: gatsby build
> 8:03:09 PM:     commandOrigin: ui
> 8:03:09 PM:     environment:
> 8:03:09 PM:       - CONTENTFUL_DELIVERY_TOKEN
> 8:03:09 PM:       - CONTENTFUL_SPACE_ID
> 8:03:09 PM:     publish: /opt/build/repo/public
> 8:03:10 PM: Caching artifacts
> 8:03:10 PM: Started saving node modules
> 8:03:10 PM: Finished saving node modules
> 8:03:10 PM: Started saving build plugins
> 8:03:10 PM: Finished saving build plugins
> 8:03:10 PM: Started saving pip cache
> 8:03:10 PM: Finished saving pip cache
> 8:03:10 PM: Started saving emacs cask dependencies
> 8:03:10 PM: Finished saving emacs cask dependencies
> 8:03:10 PM: Started saving maven dependencies
> 8:03:10 PM: Finished saving maven dependencies
> 8:03:10 PM: Started saving boot dependencies
> 8:03:10 PM: Finished saving boot dependencies
> 8:03:10 PM: Started saving go dependencies
> 8:03:10 PM: Finished saving go dependencies
> 8:03:13 PM: Error running command: Build script returned non-zero exit code: 1
> 8:03:13 PM: Failing build: Failed to build site
> 8:03:13 PM: Failed during stage 'building site': Build script returned non-zero exit code: 1
> 8:03:13 PM: Finished processing build request in 1m48.636974151s

**Comment by wkocjan** [comment]
Hey, glad you like the starter - thanks!

Your log contains this error message:

`Contentful space ID and the access token need to be provided.`

So please be sure to set env variables in your Netlify dashboard:

`Settings > Build & deploy > Environment > Environment variables`

More information:
https://docs.netlify.com/configure-builds/environment-variables/

**Comment by piyawill** [comment]
Thank you for the reply! I did put my Contentful Space ID and access token in. It works locally and I was able to test it by editing my posts on Contentful.

However, when I try to deploy it on Netlify, it does not work! And I am not sure why, because locally, the API keys are being read correctly. The keys are shown in the .env file as well.

**Comment by wkocjan** [comment]
Netlify doesn't read your `.env` file - you need to specify your credentials in Netlify panel.

The theme's demo is hosted also on Netlify, here is screenshot from my settings:

![netlify](https://user-images.githubusercontent.com/595440/93351423-055d1780-f83a-11ea-9c4a-2ee4815cfb5d.png)

Are you sure you added these variables (like above) in your Netlify settings?

**Comment by piyawill** [comment]
Hello!

Yes, I have already added those, although I did not have the Mailchimp variable. I added it now, and I received the error again.

<img width="944" alt="Screen Shot 2020-09-16 at 9 45 27 AM" src="https://user-images.githubusercontent.com/5272954/93353810-f8bccd00-f801-11ea-9f1b-26788a8e76cb.png">

I am sorry to keep being a bother! I am not sure what I am doing wrong. I did try to update dependencies, but this broke things and I had to roll back.

Here is the updated deploy log:

> 9:43:12 AM: Build ready to start
> 9:43:14 AM: build-image version: b0258b965567defc4a2d7e2f2dec2e00c8f73ad6
> 9:43:14 AM: build-image tag: v3.4.1
> 9:43:14 AM: buildbot version: 8c957a6d09a03023cea4239847cc73a9cb64eeb7
> 9:43:14 AM: Building without cache
> 9:43:14 AM: Starting to prepare the repo for build
> 9:43:14 AM: No cached dependencies found. Cloning fresh repo
> 9:43:14 AM: git clone https://github.com/piyawill/portfolio
> 9:43:15 AM: Preparing Git Reference refs/heads/master
> 9:43:16 AM: Different publish path detected, going to use the one specified in the Netlify configuration file: 'public' versus 'public/' in the Netlify UI
> 9:43:16 AM: Starting build script
> 9:43:16 AM: Installing dependencies
> 9:43:16 AM: Python version set to 2.7
> 9:43:18 AM: v12.18.0 is already installed.
> 9:43:18 AM: Now using node v12.18.0 (npm v6.14.4)
> 9:43:18 AM: Started restoring cached build plugins
> 9:43:18 AM: Finished restoring cached build plugins
> 9:43:18 AM: Attempting ruby version 2.7.1, read from environment
> 9:43:19 AM: Using ruby version 2.7.1
> 9:43:20 AM: Using PHP version 5.6
> 9:43:20 AM: 5.2 is already installed.
> 9:43:20 AM: Using Swift version 5.2
> 9:43:20 AM: Started restoring cached node modules
> 9:43:20 AM: Finished restoring cached node modules
> 9:43:20 AM: Installing NPM modules using NPM version 6.14.4
> 9:44:17 AM: > sharp@0.25.4 install /opt/build/repo/node_modules/sharp
> 9:44:17 AM: > (node install/libvips && node install/dll-copy && prebuild-install --runtime=napi) || (node-gyp rebuild && node install/dll-copy)
> 9:44:17 AM: info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.9.1/libvips-8.9.1-linux-x64.tar.gz
> 9:44:19 AM: > core-js@2.6.11 postinstall /opt/build/repo/node_modules/babel-runtime/node_modules/core-js
> 9:44:19 AM: > node -e "try{require('./postinstall')}catch(e){}"
> 9:44:19 AM: > core-js@3.6.5 postinstall /opt/build/repo/node_modules/core-js
> 9:44:19 AM: > node -e "try{require('./postinstall')}catch(e){}"
> 9:44:20 AM: > core-js-pure@3.6.5 postinstall /opt/build/repo/node_modules/core-js-pure
> 9:44:20 AM: > node -e "try{require('./postinstall')}catch(e){}"
> 9:44:21 AM: > gatsby-telemetry@1.3.34 postinstall /opt/build/repo/node_modules/gatsby-telemetry
> 9:44:21 AM: > node src/postinstall.js || true
> 9:44:21 AM: > mozjpeg@7.0.0 postinstall /opt/build/repo/node_modules/mozjpeg
> 9:44:21 AM: > node lib/install.js
> 9:44:22 AM:   ✔ mozjpeg pre-build test passed successfully
> 9:44:22 AM: > pngquant-bin@6.0.0 postinstall /opt/build/repo/node_modules/pngquant-bin
> 9:44:22 AM: > node lib/install.js
> 9:44:22 AM:   ✔ pngquant pre-build test passed successfully
> 9:44:22 AM: > gatsby-cli@2.12.97 postinstall /opt/build/repo/node_modules/gatsby/node_modules/gatsby-cli
> 9:44:22 AM: > node scripts/postinstall.js
> 9:44:22 AM: > gatsby@2.24.60 postinstall /opt/build/repo/node_modules/gatsby
> 9:44:22 AM: > node scripts/postinstall.js
> 9:44:23 AM: > swiper@5.4.5 postinstall /opt/build/repo/node_modules/swiper
> 9:44:23 AM: > echo "Love Swiper? Support Vladimir's work by donating or pledging on patreon: > https://patreon.com/vladimirkharlampidi
> 9:44:23 AM: "
> 9:44:23 AM: Love Swiper? Support Vladimir's work by donating or pledging on patreon: > https://patreon.com/vladimirkharlampidi
> 9:44:23 AM: > gatsby-contentful-portfolio@1.0.0 postinstall /opt/build/repo
> 9:44:23 AM: > node ./bin/hello.js
> 9:44:23 AM: Hey there! 👋
> 9:44:23 AM: Thanks for giving the gatsby-contentful-portfolio a try. 🎉
> 9:44:23 AM: To get you going really quickly this project includes a setup step.
> 9:44:23 AM: npm run setup automates the following steps for you:
> 9:44:23 AM:   - creates a config file .env
> 9:44:23 AM:   - imports a predefined content model
> 9:44:23 AM: When this is done run:
> 9:44:23 AM: gatsby develop to start a development environment at localhost:8000
> 9:44:23 AM: or
> 9:44:23 AM: gatsby build to create a production ready static site in ./public
> 9:44:25 AM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
> 9:44:25 AM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> 9:44:25 AM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
> 9:44:25 AM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> 9:44:25 AM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/babel-plugin-add-module-exports/node_modules/fsevents):
> 9:44:25 AM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> 9:44:25 AM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
> 9:44:25 AM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> 9:44:25 AM: added 3142 packages from 2035 contributors and audited 3156 packages in 64.807s
> 9:44:28 AM: 175 packages are looking for funding
> 9:44:28 AM:   run `npm fund` for details
> 9:44:28 AM: found 7 vulnerabilities (2 low, 5 high)
> 9:44:28 AM:   run `npm audit fix` to fix them, or `npm audit` for details
> 9:44:28 AM: NPM modules installed
> 9:44:28 AM: Started restoring cached go cache
> 9:44:28 AM: Finished restoring cached go cache
> 9:44:28 AM: go version go1.14.4 linux/amd64
> 9:44:28 AM: go version go1.14.4 linux/amd64
> 9:44:28 AM: Installing missing commands
> 9:44:28 AM: Verify run directory
> 9:44:29 AM: ​
> 9:44:29 AM: ┌─────────────────────────────┐
> 9:44:29 AM: │        Netlify Build        │
> 9:44:29 AM: └─────────────────────────────┘
> 9:44:29 AM: ​
> 9:44:29 AM: ❯ Version
> 9:44:29 AM:   @netlify/build 3.3.5
> 9:44:29 AM: ​
> 9:44:29 AM: ❯ Flags
> 9:44:29 AM:   deployId: 5f62248073bc7e00fe753cc8
> 9:44:29 AM:   mode: buildbot
> 9:44:29 AM: ​
> 9:44:29 AM: ❯ Current directory
> 9:44:29 AM:   /opt/build/repo
> 9:44:29 AM: ​
> 9:44:29 AM: ❯ Config file
> 9:44:29 AM:   No config file was defined: using default values.
> 9:44:29 AM: ​
> 9:44:29 AM: ❯ Context
> 9:44:29 AM:   production
> 9:44:29 AM: ​
> 9:44:29 AM: ┌───────────────────────────────────┐
> 9:44:29 AM: │ 1. Build command from Netlify app │
> 9:44:29 AM: └───────────────────────────────────┘
> 9:44:29 AM: ​
> 9:44:29 AM: $ gatsby build
> 9:44:31 AM: error We encountered an error while trying to load your site's gatsby-config. Please fix the error and try again.
> 9:44:31 AM: 
> 9:44:31 AM:   Error: Contentful space ID and the access token need to be provided.
> 9:44:31 AM:   
> 9:44:31 AM:   - gatsby-config.js:6 Object.<anonymous>
> 9:44:31 AM:     /opt/build/repo/gatsby-config.js:6:9
> 9:44:31 AM:   
> 9:44:31 AM:   - v8-compile-cache.js:178 Module._compile
> 9:44:31 AM:     [repo]/[v8-compile-cache]/v8-compile-cache.js:178:30
> 9:44:31 AM:   
> 9:44:31 AM:   - loader.js:1158 Object.Module._extensions..js
> 9:44:31 AM:     internal/modules/cjs/loader.js:1158:10
> 9:44:31 AM:   
> 9:44:31 AM:   - loader.js:986 Module.load
> 9:44:31 AM:     internal/modules/cjs/loader.js:986:32
> 9:44:31 AM:   
> 9:44:31 AM:   - loader.js:879 Function.Module._load
> 9:44:31 AM:     internal/modules/cjs/loader.js:879:14
> 9:44:31 AM:   
> 9:44:31 AM:   - loader.js:1026 Module.require
> 9:44:31 AM:     internal/modules/cjs/loader.js:1026:19
> 9:44:31 AM:   
> 9:44:31 AM:   - v8-compile-cache.js:159 require
> 9:44:31 AM:     [repo]/[v8-compile-cache]/v8-compile-cache.js:159:20
> 9:44:31 AM:   
> 9:44:31 AM:   - get-config-file.ts:30 getConfigFile
> 9:44:31 AM:     [repo]/[gatsby]/src/bootstrap/get-config-file.ts:30:20
> 9:44:31 AM:   
> 9:44:31 AM:   - initialize.ts:113 initialize
> 9:44:31 AM:     [repo]/[gatsby]/src/services/initialize.ts:113:50
> 9:44:31 AM:   
> 9:44:31 AM:   - index.ts:40 bootstrap
> 9:44:31 AM:     [repo]/[gatsby]/src/bootstrap/index.ts:40:15
> 9:44:31 AM:   
> 9:44:31 AM:   - build.ts:89 build
> 9:44:31 AM:     [repo]/[gatsby]/src/commands/build.ts:89:47
> 9:44:31 AM:   
> 9:44:31 AM: 
> 9:44:31 AM: not finished open and validate gatsby-configs - 0.051s
> 9:44:31 AM: ​
> 9:44:31 AM: ┌─────────────────────────────┐
> 9:44:31 AM: │   "build.command" failed    │
> 9:44:31 AM: └─────────────────────────────┘
> 9:44:31 AM: ​
> 9:44:31 AM:   Error message
> 9:44:31 AM:   Command failed with exit code 1: gatsby build
> 9:44:31 AM: ​
> 9:44:31 AM:   Error location
> 9:44:31 AM:   In Build command from Netlify app:
> 9:44:31 AM:   gatsby build
> 9:44:31 AM: ​
> 9:44:31 AM:   Resolved config
> 9:44:31 AM:   build:
> 9:44:31 AM:     command: gatsby build
> 9:44:31 AM:     commandOrigin: ui
> 9:44:31 AM:     environment:
> 9:44:31 AM:       - CONTENTFUL_DELIVERY_TOKEN
> 9:44:31 AM:       - CONTENTFUL_SPACE_ID
> 9:44:31 AM:       - MAILCHIMP_ENDPOINT
> 9:44:31 AM:     publish: /opt/build/repo/public
> 9:44:32 AM: Caching artifacts
> 9:44:32 AM: Started saving node modules
> 9:44:32 AM: Finished saving node modules
> 9:44:32 AM: Started saving build plugins
> 9:44:32 AM: Finished saving build plugins
> 9:44:32 AM: Started saving pip cache
> 9:44:32 AM: Finished saving pip cache
> 9:44:32 AM: Started saving emacs cask dependencies
> 9:44:32 AM: Finished saving emacs cask dependencies
> 9:44:32 AM: Started saving maven dependencies
> 9:44:32 AM: Finished saving maven dependencies
> 9:44:32 AM: Started saving boot dependencies
> 9:44:32 AM: Finished saving boot dependencies
> 9:44:32 AM: Started saving go dependencies
> 9:44:32 AM: Finished saving go dependencies
> 9:44:34 AM: Error running command: Build script returned non-zero exit code: 1
> 9:44:34 AM: Failing build: Failed to build site
> 9:44:34 AM: Failed during stage 'building site': Build script returned non-zero exit code: 1
> 9:44:34 AM: Finished processing build request in 1m20.382669195s

**Comment by piyawill** [comment]
Oh! Is it access token? Instead of delivery token? Let me try that ...

**Comment by piyawill** [comment]
Ah!

It works now! I got tripped up with the Delivery/Access token API keys, since the access key only allows you to view it once.

Thank you again for a great starter theme!
